# Sessione TA
## Numero 6

## Pacchetti
### `math`

In [1]:
import math

In [2]:
numero = 25
math.sqrt(numero)

5.0

In [3]:
math.factorial(5)

120

In [4]:
from math import factorial, sqrt

In [6]:
factorial(5)

120

In [7]:
sqrt(20)

4.47213595499958

In [8]:
import math as mt

In [9]:
mt.log(10)

2.302585092994046

Come trovare tutte le funzioni e le variabili in un pacchetto, oppure i metodi e gli attributi in un oggetto:

In [10]:
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [12]:
help(math.sqrt)

Help on built-in function sqrt in module math:

sqrt(x, /)
    Return the square root of x.



## Pacchetti
### `numpy`

In [13]:
import numpy as np

In [14]:
guadagni = [10, 5, 8, 20, 45, 2, 9]

In [17]:
guadagni = np.array( guadagni )

In [18]:
guadagni

array([10,  5,  8, 20, 45,  2,  9])

In [19]:
type(guadagni)

numpy.ndarray

In [24]:
guadagni.argmax()

4

In [25]:
guadagni[4]

45

In [28]:
help( guadagni.cumsum )

Help on built-in function cumsum:

cumsum(...) method of numpy.ndarray instance
    a.cumsum(axis=None, dtype=None, out=None)
    
    Return the cumulative sum of the elements along the given axis.
    
    Refer to `numpy.cumsum` for full documentation.
    
    See Also
    --------
    numpy.cumsum : equivalent function



In [29]:
guadagni

array([10,  5,  8, 20, 45,  2,  9])

In [30]:
guadagni.cumsum()

array([10, 15, 23, 43, 88, 90, 99])

In [31]:
guadagni.std()

13.621711361211675

In [32]:
for guadagno in guadagni:
    if guadagno > 10:
        print(guadagno)

20
45


### Masking e condizioni di estrazione

In [35]:
filtro10 = guadagni > 10

In [34]:
guadagni

array([10,  5,  8, 20, 45,  2,  9])

In [36]:
filtro10

array([False, False, False,  True,  True, False, False])

In [37]:
guadagni[ filtro10 ]

array([20, 45])

In [39]:
filtro = guadagni < 12
guadagni[ filtro ]

array([10,  5,  8,  2,  9])

#### Aggiornare pacchetti

In [40]:
pip install upgrade numpy

ERROR: Could not find a version that satisfies the requirement upgrade (from versions: none)
ERROR: No matching distribution found for upgrade
Note: you may need to restart the kernel to use updated packages.


## Esercizio slide 2

In [41]:
mat = [[0, 1, 2, 3, 4],
		[5, 6, 7, 8, 9],
		[10, 11, 12, 13, 14]]

In [42]:
type(mat)

list

In [44]:
mat[0][1]

1

In [45]:
mat[1][4]

9

In [46]:
arr = np.array(mat)

In [47]:
mat

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [48]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
arr[1, 4]

9

In [50]:
arr.shape

(3, 5)

In [51]:
len(mat)

3

In [52]:
arr.mean()

7.0

## Esercizio slide 3
### Parziale

In [53]:
math.pi

3.141592653589793

## Esercizio slide 5

In [54]:
lst = [2000, 5500, 7200, 4320, 1280, 1900,
		2500, 3900, 6410, 8150, 7100, 5350]


In [55]:
lst = np.array(lst)

In [56]:
lst.min()

1280

In [57]:
lst.max()

8150

In [60]:
filtro = lst > 4999
grandi_vendite = lst[ filtro ]

In [62]:
grandi_vendite.shape

(6,)

In [64]:
grandi_vendite.mean()

6618.333333333333

In [65]:
filtro3k = lst < 3000
piccole_vendite = lst[filtro3k]
piccole_vendite

array([2000, 1280, 1900, 2500])

In [66]:
lst.mean()

4634.166666666667

In [67]:
lst.shape

(12,)

## Esercizio slide 7

In [68]:
stipendi = np.array( [100, 200, 300, 400, 500,
				  600, 700, 800, 900, 1000] )

In [69]:
stipendi * 2

array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

## Pacchetti
### `pandas`

In [70]:
import pandas as pd

In [72]:
guadagni = [1, 4, 5, 6, 10, 4]

In [75]:
guadagni_s = pd.Series(guadagni, index=["gen", "feb", "mar", "apr", "mag", "giu"])

In [76]:
guadagni_s

gen     1
feb     4
mar     5
apr     6
mag    10
giu     4
dtype: int64

In [77]:
guadagni_s["apr"]

6

In [78]:
guadagni_s["mar":"mag"]

mar     5
apr     6
mag    10
dtype: int64

In [79]:
guadagni_s[4]

10

In [80]:
guadagni_s.mean()

5.0

In [81]:
guadagni_s * 100

gen     100
feb     400
mar     500
apr     600
mag    1000
giu     400
dtype: int64

In [84]:
mesi = list( guadagni_s.index )

In [85]:
"ago" in mesi

False

In [86]:
"apr" in mesi

True

In [90]:
df = pd.DataFrame( arr, index=["abbigliamento", "calzature", "sportivo"],
              columns=["gen", "feb", "mar", "apr", "mag"] )

In [91]:
df

gen  feb  mar  apr  mag
abbigliamento    0    1    2    3    4
calzature        5    6    7    8    9
sportivo        10   11   12   13   14

In [92]:
df.shape

(3, 5)

In [93]:
df["gen"]

abbigliamento     0
calzature         5
sportivo         10
Name: gen, dtype: int64

In [94]:
df.mean()

gen    5.0
feb    6.0
mar    7.0
apr    8.0
mag    9.0
dtype: float64

## Connessione a database MySQL

In [101]:
import os
import dotenv
import pandas as pd
from sqlalchemy import create_engine

dotenv.load_dotenv(dotenv_path=".env", override=True)

username = os.getenv("username")
password = os.getenv("password")
host = os.getenv("host")
dbname = os.getenv("dbname")

conn_string = "mysql+pymysql://" + username + ":" + password + "@" + host + "/" + dbname
db_engine = create_engine(conn_string)

query = "SELECT * FROM dimproduct"
df = pd.read_sql(sql=query, con=db_engine)

In [102]:
df

ProductKey ProductAlternateKey  ProductSubcategoryKey  \
0             1             AR-5381                    NaN   
1             2             BA-8327                    NaN   
2             3             BE-2349                    NaN   
3             4             BE-2908                    NaN   
4             5             BL-2036                    NaN   
..          ...                 ...                    ...   
601         602             BB-8107                    5.0   
602         603             BB-9108                    5.0   
603         604          BK-R19B-44                    2.0   
604         605          BK-R19B-48                    2.0   
605         606          BK-R19B-52                    2.0   

    WeightUnitMeasureCode SizeUnitMeasureCode     EnglishProductName  \
0                    None                None        Adjustable Race   
1                    None                None           Bearing Ball   
2                    None                None        BB Ball Bearing   
3                    None                None  Headset Ball Bearings   
4                    None                None                  Blade   
..                    ...                 ...                    ...   
601                     G                None      ML Bottom Bracket   
602                     G                None      HL Bottom Bracket   
603                    LB                  CM     Road-750 Black, 44   
604                    LB                  CM     Road-750 Black, 48   
605                    LB                  CM     Road-750 Black, 52   

            SpanishProductName           FrenchProductName  StandardCost  \
0                                                                    NaN   
1                                                                    NaN   
2                                                                    NaN   
3                                                                    NaN   
4                                                                    NaN   
..                         ...                         ...           ...   
601         Eje de pedalier GM          Axe de pédalier ML         44.95   
602         Eje de pedalier GA          Axe de pédalier HL         53.94   
603  Carretera: 750, negra, 44  Vélo de route 750 noir, 44        343.65   
604  Carretera: 750, negra, 48  Vélo de route 750 noir, 48        343.65   
605  Carretera: 750, negra, 52  Vélo de route 750 noir, 52        343.65   

     FinishedGoodsFlag  ...                 ChineseDescription  \
0                    0  ...                               None   
1                    0  ...                               None   
2                    0  ...                               None   
3                    0  ...                               None   
4                    0  ...                               None   
..                 ...  ...                                ...   
601                  1  ...                      铝合金车圈；大直径脚蹬轴。   
602                  1  ...                         铝合金车圈和空心轴。   
603                  1  ...  入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。   
604                  1  ...  入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。   
605                  1  ...  入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。   

                                     ArabicDescription  \
0                                                 None   
1                                                 None   
2                                                 None   
3                                                 None   
4                                                 None   
..                                                 ...   
601  فناجين من سبيكة الألومنيوم؛ ذات محور دوران كبي...   
602             فناجين من سبيكة الألومنيوم ومحور أجوف.   
603  إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...   
604  إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...   
605  إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت

In [103]:
df.shape

(606, 36)